// Mocks generated by Mockito 5.4.6 from annotations
// in bakery_app/test/features/settings/catalog_tags_settings_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bakery_app/data/api/config_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTagUsage_0 extends _i1.SmartFake implements _i2.TagUsage {
  _FakeTagUsage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i2.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.ConfigValue>> getConfigValues(String? configKey) =>
      (super.noSuchMethod(
            Invocation.method(#getConfigValues, [configKey]),
            returnValue: _i3.Future<List<_i2.ConfigValue>>.value(
              <_i2.ConfigValue>[],
            ),
          )
          as _i3.Future<List<_i2.ConfigValue>>);

  @override
  _i3.Future<void> createConfigValue(
    String? configKey,
    String? value, {
    int? sortOrder = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createConfigValue,
              [configKey, value],
              {#sortOrder: sortOrder},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateConfigValue(
    String? configKey,
    String? oldValue,
    String? newValue, {
    int? sortOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateConfigValue,
              [configKey, oldValue, newValue],
              {#sortOrder: sortOrder},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteConfigValue(String? configKey, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConfigValue, [configKey, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.TagUsage> getTagUsage(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getTagUsage, [key]),
            returnValue: _i3.Future<_i2.TagUsage>.value(
              _FakeTagUsage_0(this, Invocation.method(#getTagUsage, [key])),
            ),
          )
          as _i3.Future<_i2.TagUsage>);
}
